---
  - name: Install metric beat
    hosts: webservers
    remote_user: sysadmin
    become: true
    tasks:

      # Use command module
    # - name: Download metricbeat
    #  command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Download metricbeat deb
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
        dest: /etc/metricbeat/metricbeat.yml

      # Use command module
    - name: install metricbeat
      command: dpkg -i metricbeat-7.6.1-amd64.deb

      # Use copy module
    - name: drop in metricbeat config
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

      # Use command module
    - name: enable and configure docker module for metric beat
      command: metricbeat modules enable docker

      # Use command module
    - name: setup metric beat
      command: metricbeat setup

      # Use command module
    #- name: start metric beat
    #  command: service metricbeat start

    - name: start service metricbeat
      ansible.builtin.service:
        name: metricbeat
        state: started

      # Use systemd module
    - name: enable service metricbeat on boot
      systemd:
        name: metricbeat
        enabled: yes